#!/usr/bin/env bash
# Regenerates mobilityid/iso3166_alpha2.go, the ISO 3166-1 alpha-2 codes accepted by CountryCode,
# from the JDK's Locale.getISOCountries() (the source the Scala reference validates against).
# Needs the Java version pinned in ../mise.toml. Usage, from go/: scripts/generate-iso3166.sh
set -euo pipefail

cd "$(dirname "$0")/.."
out=mobilityid/iso3166_alpha2.go

codes=$(java scripts/Iso3166Codes.java)
count=$(printf '%s\n' "$codes" | wc -l | tr -d ' ')

{
  cat <<'HEADER'
/*
 * Copyright (c) 2014 The New Motion team, and respective contributors
 * Copyright (c) 2026 Julien Herr, and respective contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by scripts/generate-iso3166.sh; DO NOT EDIT.

package mobilityid

HEADER
  printf '// iso3166Alpha2 lists the %s ISO 3166-1 alpha-2 codes returned by the JDK'"'"'s\n' "$count"
  printf '// Locale.getISOCountries(), the reference the Scala library validates country codes against.\n'
  printf 'var iso3166Alpha2 = map[string]struct{}{\n'
  printf '%s\n' "$codes" | awk '{ printf "\t\"%s\": {},\n", $1 }'
  printf '}\n'
} > "$out"

gofmt -l "$out" >/dev/null
echo "wrote $out ($count codes)"
