#!/usr/bin/env bash
# Regenerates mobilityid/iso3166_alpha2.go, the ISO 3166-1 alpha-2 codes accepted by CountryCode,
# from the JDK's Locale.getISOCountries() (the source the Scala reference validates against).
# Needs the Java version pinned in ../mise.toml. Usage, from go/: scripts/generate-iso3166.sh
set -euo pipefail

cd "$(dirname "$0")/.."
out=mobilityid/iso3166_alpha2.go

codes=$(java scripts/Iso3166Codes.java)
count=$(printf '%s\n' "$codes" | grep -c '^[A-Z][A-Z]$' || true)
if [ "$count" -lt 200 ] || [ "$count" -ne "$(printf '%s\n' "$codes" | wc -l | tr -d ' ')" ]; then
  echo "unexpected generator output: $count two-letter codes" >&2
  exit 1
fi

{
  # Same license header as every source file; goheader validates it.
  sed -n '1,/^ \*\/$/p' mobilityid/doc.go
  printf '\n// Code generated by scripts/generate-iso3166.sh; DO NOT EDIT.\n\npackage mobilityid\n\n'
  printf '// iso3166Alpha2 lists the %s ISO 3166-1 alpha-2 codes returned by the JDK'"'"'s\n' "$count"
  printf '// Locale.getISOCountries(), the reference the Scala library validates country codes against.\n'
  printf 'var iso3166Alpha2 = map[string]struct{}{\n'
  printf '%s\n' "$codes" | awk '{ printf "\t\"%s\": {},\n", $1 }'
  printf '}\n'
} | gofmt > "$out"

echo "wrote $out ($count codes)"
