#!/usr/bin/env bash
#
# Copyright (c) 2026 Julien Herr, and respective contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Regenerates src/iso3166-alpha2.ts, the ISO 3166-1 alpha-2 codes accepted by CountryCode, from
# the JDK's Locale.getISOCountries() through the Go port's generator source, so both generated
# tables come from the same list. Needs the Java version pinned in ../mise.toml.
# Usage, from ts/: scripts/generate-iso3166.sh          rewrites src/iso3166-alpha2.ts
#                  scripts/generate-iso3166.sh --check  fails when the committed file is stale
set -euo pipefail

cd "$(dirname "$0")/.."
committed=src/iso3166-alpha2.ts
out="$committed"
if [ "${1:-}" = "--check" ]; then
  out=$(mktemp -t iso3166-alpha2.XXXXXX)
  trap 'rm -f "$out"' EXIT
fi

codes=$(java ../go/scripts/Iso3166Codes.java)
count=$(printf '%s\n' "$codes" | grep -c '^[A-Z][A-Z]$' || true)
if [ "$count" -lt 200 ] || [ "$count" -ne "$(printf '%s\n' "$codes" | wc -l | tr -d ' ')" ]; then
  echo "unexpected generator output: $count two-letter codes" >&2
  exit 1
fi

{
  cat license-header.txt
  printf '\n// Code generated by scripts/generate-iso3166.sh; DO NOT EDIT.\n\n'
  printf '/**\n * The %s ISO 3166-1 alpha-2 codes returned by the JDK'"'"'s `Locale.getISOCountries()`, the\n' "$count"
  printf ' * reference the Scala library validates country codes against. Sorted.\n */\n'
  printf 'export const ISO_3166_ALPHA2 = [\n'
  printf '%s\n' "$codes" | awk '{ printf "  \"%s\",\n", $1 }'
  printf '] as const;\n'
} > "$out"


if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$committed" "$out"; then
    echo "$committed is stale: run scripts/generate-iso3166.sh and commit the result" >&2
    exit 1
  fi
  echo "$committed is up to date ($count codes)"
else
  echo "wrote $out ($count codes)"
fi
