rules = [
  OrganizeImports
  RemoveUnused
]
OrganizeImports {
  groupedImports = Merge
  groups = ["scala.", "java.", "javax.", "*", "com.thenewmotion."]
  removeUnused = true
  targetDialect = Scala2
}
